table UG_INSEE
	lineageTag: b66f6bb0-c6e0-4f92-b7af-7ead229b2129

	column code_ug
		dataType: string
		lineageTag: ab4171e9-338d-4d93-8a24-4f6f9662073b
		summarizeBy: none
		sourceColumn: code_ug

		annotation SummarizationSetBy = Automatic

	column code_insee
		dataType: string
		lineageTag: d877fffe-2da7-44f1-9955-052e34588f77
		summarizeBy: none
		sourceColumn: code_insee

		annotation SummarizationSetBy = Automatic

	column Commune = ```
			SWITCH(
			    'UG_INSEE'[code_insee],
			    "02", "Bras-Panon",
			    "24", "Cilaos",
			    "03", "Entre-Deux",
			    "04", "L'Étang-Salé",
			    "06", "La Plaine-des-Palmistes",
			    "08", "La Possession",
			    "07", "Le Port",
			    "22", "Le Tampon",
			    "01", "Les Avirons",
			    "23", "Les Trois-Bassins",
			    "05", "Petite-Île",
			    "09", "Saint-André",
			    "10", "Saint-Benoît",
			    "11", "Saint-Denis",
			    "18", "Sainte-Marie",
			    "19", "Sainte-Rose",
			    "20", "Sainte-Suzanne",
			    "12", "Saint-Joseph",
			    "13", "Saint-Leu",
			    "14", "Saint-Louis",
			    "15", "Saint-Paul",
			    "17", "Saint-Philippe",
			    "16", "Saint-Pierre",
			    "21", "Salazie",
			    BLANK() -- Si aucun match n'est trouvé
			)
			
			```
		lineageTag: fb0bd9bc-d160-4177-af8f-4ac160ec0b00
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition UG_INSEE = m
		mode: import
		source =
				let
				    Source = PatrimoineSrhEnGestionDepuis2023,
				    #"Autres colonnes supprimées" = Table.SelectColumns(Source,{"code_ug", "code_insee"}),
				    #"Doublons supprimés" = Table.Distinct(#"Autres colonnes supprimées", {"code_ug"})
				in
				    #"Doublons supprimés"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

